### ISSUE TITLE
Aggiornare i metodi client 

### ISSUE THREAD

**Issue by capponiFelice92** [luca-lezzerini/rubrica-his#10]
Aggiornare i metodi client con l'argomento dell'osservabile giusto e aggiornare risposte rest inserendo nella rubrica visualizzata la proprietà "rubrica" della classe ResRubricaDto.

**Comment by moretti-matteo** [comment]
- ho aggiornato ogni metodo del client inserendo nella rubrica visualizzata la proprietà "rubrica" della classe "ResRubricaDto"
- ho cambiato l'argomento dell'osservabile di ogni metodo da "<ReqContattoDto[]" a "\<ResRubricaDto>"

![image](https://user-images.githubusercontent.com/78532093/107380863-8e793180-6aee-11eb-82ad-810760628b57.png)

**Comment by capponiFelice92** [comment]
Perfetto
