### ISSUE TITLE
I dto sono sempre necessari?

### ISSUE THREAD

**Issue by capponiFelice92** [luca-lezzerini/rubrica-his#11]
Nel caso della rubrica noi li stiamo utilizzando ma mi sorgeva il dubbio se fossero proprio necessari in quanto la classe ReqContattoDto potrebbe tranquillamente chiamarsi Contatto e il software funzionerebbe ancora, inoltre apparentemente l'uso della ResRubricaDto sembra quasi un "di più" in quanto potremmo trasmettere al client direttamente anche la List<> che è una proprietà del ServiceImpl, senza prima inscatolarla dentro il ResRubricaDto.

**Comment by luca-lezzerini** [comment]
Il suo commento è corretto e spesso si fa così. Ci sono comunque alcune ragioni per fare tramite DTO, che valgono in moltissimi casi:

1. Se cambiano i dati scambiati (es. trasferisco la lista di contatti e poi mi serve anche un codice numerico per la sicurezza) usando il DTO l'interfaccia non cambia. Usando direttamente l'entità invece cambia.
2. Scambiando l'entità si possono inviare al client dati indesiderati (es. la password di un utente o i prezzi di acquisto di un prodotto) che oltre a consumare banda creano problemi di security
3. Altri motivi che non è il caso di riportare qui.

**Comment by capponiFelice92** [comment]
capito, grazie.
