### ISSUE TITLE
controllo input vuoti client

### ISSUE THREAD

**Issue by capponiFelice92** [luca-lezzerini/rubrica-his#12]
Inserire un controllo nel metodo aggiungi del client, per evitare di inserire contatti con campi vuoti;
Far apparire un messaggio su interfaccia utente che dice "Uno o più campi non sono stati compilati".

**Comment by moretti-matteo** [comment]
Risolto, adesso quando si inserisce un utente con i vari campi vuoti appare un messaggio di errore
![image](https://user-images.githubusercontent.com/78532093/107405393-8ed1f680-6b07-11eb-8584-fb14187a8463.png)

**Comment by capponiFelice92** [comment]
credo sia opportuno dare un messaggio di errore più chiaro, che spieghi all'utente quale è il problema esatto che non lo fa proseguire (nel nostro caso l'errore lo diamo solo per campi vuoti, ma in futuro potremmo dare un errore anche se si cerca di inserire ad esempio un numero di telefono troppo corto, troppo lungo, con caratteri speciali o lettere in generale)
Per quanto riguarda il funzionamento è perfetto, bella l'animazione! :-)

**Comment by moretti-matteo** [comment]
ho fatto in modo che a seconda dei campi vuoti vengono visualizzati i relativi "errori".  che ne pensi? troppo dettagliato o può andare bene?
![image](https://user-images.githubusercontent.com/78532093/107424963-9bae1480-6b1e-11eb-8d49-de960f46d55b.png)

**Comment by capponiFelice92** [comment]
bello, ben fatto!
