### ISSUE TITLE
è possibile mettere l'istruzione IF nelle lambda?

### ISSUE THREAD

**Issue by moretti-matteo** [luca-lezzerini/rubrica-his#13]
sto facendo delle prove e quando vado ad inserire l'istruzione IF come seconda istruzione della lambda mi riporta l'errore: 
     **_Expression expected._**
è possibile eseguire istruzioni di questo tipo nelle lambda? o vanno bene solo istruzioni del tipo variabile1 = variabile2 ?
![image](https://user-images.githubusercontent.com/78532093/107482733-64704f80-6b80-11eb-814a-3d06b50e71b9.png)
![image](https://user-images.githubusercontent.com/78532093/107482786-73570200-6b80-11eb-8e8e-fafa6407415c.png)

**Comment by luca-lezzerini** [comment]
Manca il ; dopo l'ultima tonda nell'ultima riga!!!!!!!!!!!!

**Comment by luca-lezzerini** [comment]
E faccia Alt+Shift+F!!!!!!!

**Comment by moretti-matteo** [comment]
provai anche con il punto e virgola ma mi dice sempre Expression expected, per questo ho chiesto se si potesse mettere l'istruzione IF in quel punto.
![image](https://user-images.githubusercontent.com/78532093/107487596-a13f4500-6b86-11eb-82a3-f350aeb528b0.png)

**Comment by luca-lezzerini** [comment]
Manca altro ; dopo risp.rubrica alla riga 122!!!!!!!!!!!!!!
Questi problemi li dovete risolvere da soli nel gruppo.

**Comment by moretti-matteo** [comment]
risolto, grazie
