### ISSUE TITLE
bug client

### ISSUE THREAD

**Issue by capponiFelice92** [luca-lezzerini/rubrica-his#15]
quando apro il client su browser, cliccando recupera contatti appare la tabella con tutti i contatti ma anche un messaggio di errore che dice "nessun contatto recuperato, inseriscine qualcuno".
![Senza titolo - Google Chrome 14_02_2021 20_26_12](https://user-images.githubusercontent.com/78529321/107886994-62e9b300-6f03-11eb-981e-f72ab5fdfeca.png)

**Comment by moretti-matteo** [comment]
dovrei aver risolto il problema
![image](https://user-images.githubusercontent.com/78532093/107888784-d644f200-6f0e-11eb-9e2f-115c93c781fd.png)

**Comment by capponiFelice92** [comment]
Verificato, ben fatto!
