### ISSUE TITLE
Commenti mancanti

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/rubrica-his#5]
Commentare il codice

**Comment by capponiFelice92** [comment]
inserisci commenti in tutto il codice, sia server che client dove ritieni che il codice sia poco chiaro, per chiarimenti contattare Felice per il server, Matteo per il client.

**Comment by capponiFelice92** [comment]
chiuso per sbaglio

**Comment by nicoloabatecola** [comment]
Completato
