### ISSUE TITLE
risolvere bug di visualizzazione client

### ISSUE THREAD

**Issue by capponiFelice92** [luca-lezzerini/rubrica-his#9]
Risolvere bug di visualizzazione:
![RubricaClient - Google Chrome 08_02_2021 18_40_35](https://user-images.githubusercontent.com/78529321/107259344-2b7b9200-6a3d-11eb-8263-501e5d1cd904.png)

alla pressione del tasto cancella deve apparire conferma/annulla (si/no) solo per la riga dove è stato premuto il bottone "X".

**Comment by moretti-matteo** [comment]
Bug risolto! ora alla pressione del tasto cancella appaiono i pulsanti conferma/annulla solo nella riga selezionata
![image](https://user-images.githubusercontent.com/78532093/107396991-8e812d80-6afe-11eb-89d9-430d776f1404.png)

**Comment by capponiFelice92** [comment]
perfetto
